GlobalListContents {
    contents: Mutex {
        data: [
            Global { name: 1, interface: "wl_seat", version: 9 },
            Global { name: 2, interface: "wl_data_device_manager", version: 3 },
            Global { name: 3, interface: "wl_compositor", version: 6 },
            Global { name: 4, interface: "wl_subcompositor", version: 1 },
            Global { name: 5, interface: "wl_shm", version: 1 },
            Global { name: 6, interface: "wp_viewporter", version: 1 },
            Global { name: 7, interface: "wp_tearing_control_manager_v1", version: 1 },
            Global { name: 8, interface: "wp_fractional_scale_manager_v1", version: 1 },
            Global { name: 9, interface: "zxdg_output_manager_v1", version: 3 },
            Global { name: 10, interface: "wp_cursor_shape_manager_v1", version: 1 },
            Global { name: 11, interface: "zwp_idle_inhibit_manager_v1", version: 1 },
            Global { name: 12, interface: "zwp_relative_pointer_manager_v1", version: 1 },
            Global { name: 13, interface: "zxdg_decoration_manager_v1", version: 1 },
            Global { name: 14, interface: "wp_alpha_modifier_v1", version: 1 },
            Global { name: 15, interface: "zwlr_gamma_control_manager_v1", version: 1 },
            Global { name: 16, interface: "ext_foreign_toplevel_list_v1", version: 1 },
            Global { name: 17, interface: "zwp_pointer_gestures_v1", version: 3 },
            Global { name: 18, interface: "zwlr_foreign_toplevel_manager_v1", version: 3 },
            Global { name: 19, interface: "zwp_keyboard_shortcuts_inhibit_manager_v1", version: 1 },
            Global { name: 20, interface: "zwp_text_input_manager_v1", version: 1 },
            Global { name: 21, interface: "zwp_text_input_manager_v3", version: 1 },
            Global { name: 22, interface: "zwp_pointer_constraints_v1", version: 1 },
            Global { name: 23, interface: "zwlr_output_power_manager_v1", version: 1 },
            Global { name: 24, interface: "xdg_activation_v1", version: 1 },
            Global { name: 25, interface: "ext_idle_notifier_v1", version: 2 },
            Global { name: 26, interface: "hyprland_lock_notifier_v1", version: 1 },
            Global { name: 27, interface: "ext_session_lock_manager_v1", version: 1 },
            Global { name: 28, interface: "zwp_input_method_manager_v2", version: 1 },
            Global { name: 29, interface: "zwp_virtual_keyboard_manager_v1", version: 1 },
            Global { name: 30, interface: "zwlr_virtual_pointer_manager_v1", version: 2 },
            Global { name: 31, interface: "zwlr_output_manager_v1", version: 4 },
            Global { name: 32, interface: "org_kde_kwin_server_decoration_manager", version: 1 },
            Global { name: 33, interface: "hyprland_focus_grab_manager_v1", version: 1 },
            Global { name: 34, interface: "zwp_tablet_manager_v2", version: 1 },
            Global { name: 35, interface: "zwlr_layer_shell_v1", version: 5 },
            Global { name: 36, interface: "wp_presentation", version: 2 },
            Global { name: 37, interface: "xdg_wm_base", version: 7 },
            Global { name: 38, interface: "zwlr_data_control_manager_v1", version: 2 },
            Global { name: 39, interface: "zwp_primary_selection_device_manager_v1", version: 1 },
            Global { name: 40, interface: "xwayland_shell_v1", version: 1 },
            Global { name: 41, interface: "zwlr_screencopy_manager_v1", version: 3 },
            Global { name: 42, interface: "hyprland_toplevel_export_manager_v1", version: 2 },
            Global { name: 43, interface: "hyprland_toplevel_mapping_manager_v1", version: 1 },
            Global { name: 44, interface: "hyprland_global_shortcuts_manager_v1", version: 1 },
            Global { name: 45, interface: "xdg_wm_dialog_v1", version: 1 },
            Global { name: 46, interface: "wp_single_pixel_buffer_manager_v1", version: 1 },
            Global { name: 47, interface: "wp_security_context_manager_v1", version: 1 },
            Global { name: 48, interface: "hyprland_ctm_control_manager_v1", version: 2 },
            Global { name: 49, interface: "hyprland_surface_manager_v1", version: 2 },
            Global { name: 50, interface: "wp_content_type_manager_v1", version: 1 },
            Global { name: 51, interface: "xdg_toplevel_tag_manager_v1", version: 1 },
            Global { name: 52, interface: "xdg_system_bell_v1", version: 1 },
            Global { name: 53, interface: "ext_workspace_manager_v1", version: 1 },
            Global { name: 54, interface: "ext_data_control_manager_v1", version: 1 },
            Global { name: 55, interface: "wp_pointer_warp_v1", version: 1 },
            Global { name: 56, interface: "wp_color_manager_v1", version: 1 },
            Global { name: 57, interface: "wp_drm_lease_device_v1", version: 1 },
            Global { name: 58, interface: "wp_linux_drm_syncobj_manager_v1", version: 1 },
            Global { name: 59, interface: "wp_drm_lease_device_v1", version: 1 },
            Global { name: 60, interface: "wl_drm", version: 2 },
            Global { name: 61, interface: "zwp_linux_dmabuf_v1", version: 5 },
            Global { name: 62, interface: "wl_output", version: 4 }
        ], poisoned: false, ..
    }
}
